
# For Java 11, try this
FROM openjdk:11 as build

#Refer to Maven build -> finalName
ARG JAR_FILE=charafpfe/target/charafpfe.jar

# cd /opt/app
WORKDIR /opt/app

# cp target/charafpfe.jar /opt/app/charafpfe.jar
COPY ${JAR_FILE} charafpfe.jar

# java -jar /opt/app/charafpfe.jar
ENTRYPOINT ["java","-jar","charafpfe.jar"]


#
# BUILD STAGE
#
FROM maven:3.6.3-jdk-11-slim AS build  
WORKDIR /usr/src/app/src
#COPY charafpfe/src /usr/src/app/src
COPY src /usr/src/app/src  
#COPY charafpfe/pom.xml /usr/src/app
COPY pom.xml /usr/src/app  
RUN mvn -f /usr/src/app/pom.xml clean install

#
# PACKAGE STAGE
#
FROM openjdk:11-jre-slim
COPY --from=build /usr/src/app/target/charafpfe.jar /usr/app/charafpfe.jar  
EXPOSE 7007  
CMD ["java","-jar","/usr/app/charafpfe.jar"] 

